spring:
  application:
    name: sudoku-test-task
  config:
    import: "optional:file:src\\test\\resources\\.env[.properties]"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8080

