spring:
  application:
    name: sudoku-test-task
  config:
    import: "optional:file:src\\test\\resources\\.env[.properties]"
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        same-site: none
        secure: false
