spring:
  application:
    name: sudoku-test-task
  config:
    import: "optional:file:src\\main\\resources\\.env[.properties]"
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: false
        same-site: none
        secure: true
        path: ""

