name: Gradle Build Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATA_DIRECTORY: ${{ github.workspace }}/${{ vars.RELATIVE_DATA_DIRECTORY }}
      FILE_SECTION_SPLITTER: ${{ vars.FILE_SECTION_SPLITTER }}
      SUDOKU_FILE_PREFIX: ${{ vars.SUDOKU_FILE_PREFIX }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build
